@startuml strategie
title Strategie v organizaci
footer 
© 2022 EGOVedu, EGdílna.cz
github.com/egdilna/egovedu
end footer
!include <archimate/archimate>
left to right direction
Business_Actor(metamodelorganizace, "Organizace") 
Business_Contract(metamodelbyzstrategie, "Strategie organizace") 
Business_Contract(metamodelitstrategie, "Strategie rozvoje IT") 
Business_Contract(metamodelikovs, "Informační koncepce úřadu") 
Motivation_Goal(metamodelbyzstratcil, "Strategický cíl organizace") 
Motivation_Goal(metamodelitcil, "Cíl rozvoje IT") 
Motivation_Principle(metamodelprincip, "Architektonický princip") 
Motivation_Principle(metamodelzasada, "Zásada řízení") 
Implementation_WorkPackage(metamodelprojekt, "Projekt") 
Rel_Serving(metamodelorganizace, metamodelbyzstrategie, vydává)
Rel_Serving(metamodelorganizace, metamodelitstrategie, vydává)
Rel_Specialization(metamodelitstrategie, metamodelikovs, "pro ovm")
Rel_Association(metamodelbyzstrategie, metamodelbyzstratcil, určuje)
Rel_Association(metamodelitstrategie, metamodelitcil, určuje)
Rel_Association(metamodelitstrategie, metamodelprincip, určuje)
Rel_Association(metamodelitstrategie, metamodelzasada, určuje)
Rel_Association(metamodelprojekt, metamodelitcil, realizuje)
Rel_Association(metamodelprojekt, metamodelprincip, plní)
Rel_Association(metamodelprojekt, metamodelzasada, plní)
@enduml

@startuml isvs-role 
title ISVS a vztahy a důležité role
footer 
© 2022 EGOVedu, EGdílna.cz
github.com/egdilna/egovedu
end footer
!include <archimate/archimate>
left to right direction
Business_Actor(ovm, "Orgán veřejné moci") 
Application_Component(isvs, "Informační systém veřejné správy") 
Application_Component(ais, "Agendový informační systém") 
Business_Role(rolespravceisvs, "Správce informačního systému") 
Business_Role(roleuzivatelis, "Uživatel informačního systému") 
Business_Role(roleeditorudajiis, "Editor údajů v agendovém informačním systému") 
Business_Role(roleuzivateludajuis, "Uživatel údajů v informačním systému") 
Rel_Serving(ovm, isvs, spravuje)
Rel_Serving(isvs, ovm, je užíván)
Rel_Specialization(isvs, ais)
Rel_Assignment(ovm, rolespravceisvs)
Rel_Assignment(ovm, roleeditorudajiis)
Rel_Assignment(ovm, roleuzivatelis)
Rel_Assignment(ovm, roleuzivateludajuis)
@enduml

@startuml druhy-subjekty
title Druhy subjektů a jejich zdroje
footer 
© 2022 EGOVedu, EGdílna.cz
github.com/egdilna/egovedu
end footer
!include <archimate/archimate>
left to right direction
Business_Actor(subjekt, "Subjekt") 
Business_Actor(subjektfo, "Fyzická osoba") 
Business_Actor(subjektpo, "Právnická osoba") 
Business_Actor(subjektpfo, "Podnikající fyzická osoba") 
Business_Actor(subjektosvc, "Osoba samostatně výdělečně činná") 
Business_Actor(forobak, "Fyzická osoba vedená v Registru obyvatel") 
Business_Actor(fonerobak, "Fyzická osoba, která není vedena v Registru obyvatel") 
Business_Actor(pobockaros, "Pobočka osoby") 
Business_Actor(pojevros, "Právnický subjekt vedený v Registru osob") 
Business_Actor(ponenivros, "Právnický subjekt, který není vedený v Registru osob") 
Grouping(zr, "Základní registry") {
    Application_Component(rob, "Registr obyvatel (ROB)") 
    Application_Component(ros, "Registr osob (ROS)") 
}
    Rel_Specialization(subjekt, subjektfo)
Rel_Specialization(subjektfo, forobak)
Rel_Specialization(subjektfo, fonerobak)
Rel_Specialization(subjekt, subjektpo)
Rel_Serving(subjektfo, subjektpo)
Rel_Specialization(subjektpo, subjektpfo)
Rel_Specialization(subjektpo, subjektosvc)
Rel_Specialization(subjektpo, pojevros)
Rel_Specialization(subjektpo, ponenivros)
Rel_Composition(subjektpo, pobockaros)
Rel_Access(rob, forobak)
Rel_Access(ros, pobockaros)
Rel_Access(ros, pojevros)
@enduml

@startuml skupiny-udaju-subjektu
title Druhy a skupiny údajů o subjektu
footer 
© 2022 EGOVedu, EGdílna.cz
github.com/egdilna/egovedu
end footer
!include <archimate/archimate>
left to right direction
Grouping(groupingskupinyudajusu, "Skupiny údajů o subjektu") {
    Application_DataObject(udajeref, "Referenční údaje") 
    Application_DataObject(udajeneref, "Nereferenční údaje ze základních registrů") 
    Application_DataObject(udajekontaktni, "Kontaktní údaje") 
    Application_DataObject(udajezsrpp, "Údaje o zápisu skutečnosti v RPP") 
    Application_DataObject(udajeagendove, "Agendové údaje") 
    Application_DataObject(udajeovu, "Údaje o využití údajů subjektu") 
    Application_DataObject(udajeprocesni, "Procesní údaje") 
    Application_DataObject(udajeprovozni, "Provozní údaje") 
}
@enduml

@startuml prehledikovsadopceikcr
title Adopce a vztah IKČR a IK úřadutitle Adopce a vztah IKČR a IK úřadu
footer 
© 2022 EGOVedu, EGdílna.cz
github.com/egdilna/egovedu
end footer
!include <archimate/archimate>
left to right direction
Business_Actor(mv, "Ministerstvo vnitra") 
Business_Contract(ikcr, "Informační koncepce ČR") 
Rel_Association(mv, ikcr)

Business_Actor(ovm, "Orgán veřejné moci") 
Business_Contract(metamodelikovs, "Informační koncepce úřadu") 
Grouping(groupingikcrovmitcile, "Cíle rozvoje ITúřadu")  {
    Grouping(groupingikcrcile, "Národní cíle IKČR ") 
    Motivation_Goal(itciladopcepzikcr, "Řádná adopce architektonických principů a zásad řízení z informační koncepce Čr") 
    Motivation_Goal(itcilnasecilecileikcr, "Stanovení cílů a realizace projektů pro naplnění národních cílů z IKČR") 
    Motivation_Goal(metamodelitcil, "Cíl rozvoje IT") 
}
Grouping(groupingikcrovmitpz, "Principy a zásady úřadu") {
    Grouping(groupingikcrarchprincipy, "Národní  architektonické principy") 
    Grouping(groupingikcrzasady, "Národní  zásady řízení") 
    Motivation_Principle(metamodelprincip, "Architektonický princip") 
    Motivation_Principle(metamodelzasada, "Zásada řízení") 
}
Implementation_WorkPackage(metamodelprojekt, "Projekt") 
Rel_Composition(ikcr, groupingikcrarchprincipy)
Rel_Composition(ikcr, groupingikcrcile)
Rel_Composition(ikcr, groupingikcrzasady)

Rel_Association(ovm, metamodelikovs)
Rel_Realization(metamodelikovs, metamodelprincip)
Rel_Realization(metamodelikovs, metamodelzasada)
Rel_Aggregation(ikcr, metamodelikovs)
Rel_Composition(metamodelikovs, groupingikcrovmitcile)
Rel_Composition(metamodelikovs, groupingikcrovmitpz)
Rel_Association(metamodelikovs, metamodelprojekt)
Rel_Association(metamodelikovs, ovm)
Rel_Specialization(metamodelitstrategie, metamodelikovs)
@enduml